<?php

/**
 * @file
 * Top Search module.
 */
  
/**
 * Implements hook_menu().
 */
function wcs_top_search_menu() {
  $items = array();
  
  $items['related-search/json'] = array(
    'title' => 'Related search',
    'page callback' => 'wcs_top_search_related',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK ,
  );
  return $items;
}

/**
 * Update count in wcs_top_search table.
 */
function wcs_top_search_update($keyword) {
  if (empty($keyword)) return;
  
  // get count from keyword;
  $results = db_query("SELECT count FROM {wcs_top_search} WHERE keyword = :keyword", array(':keyword' => $keyword))->fetchAll();
  
  $count = 0;
  foreach ($results as $result) {
    $count = $result->count;
  }
  
  $count++;
  
  $fields = array(
    'keyword' => $keyword,
    'count' => $count,
  );
  // update count in wcs_top_search table
  db_merge('wcs_top_search')
    ->key(array('keyword' => $keyword))
    ->fields($fields)
    ->execute();

}
/**
 * Return JSON output from related search.
 */
function wcs_top_search_related() {
  $string = @$_REQUEST['keywords'];
  $results = array('keywords' => array());
  
  // Related  keywords
  $result = db_select('wcs_top_search')->fields('wcs_top_search', array('keyword'))
          ->condition('keyword', db_like($string) . '%', 'LIKE')
          ->execute()->fetchCol();

  $results['keywords'] = $result;
  
  drupal_json_output($results);
}






