<?php

/**
 * @file
 * Content filter module.
 */

/**
 * Implements hook_menu().
 */
function content_filter_menu() {
  
  $order_types = content_filter_get_types();
  // add filter pages for special content types
  $types = node_type_get_types();
  if (!empty($order_types)) {
    $key = 0;
    foreach ($order_types as $type => $title) {
      $key++;
      $items['admin/content/' . $type] = array(
        'title' => $title,
        'description' => "View, edit, and delete " . $title . " content.",
        'page callback' => 'drupal_get_form',
        'page arguments' => array('content_filter_content_by_type', 2),
        'access arguments' => array('administer nodes'),
        'file' => 'content_filter.admin.inc',
        'weight' => '-' . $key,
        'type' => MENU_LOCAL_TASK,
      );
    }  
  }
  $items['admin/config/content/node_order'] = array(
    'title' => 'Content filter setting',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('content_filter_setting_form'),
    'access arguments' => array('administer nodes'),
    'file' => 'content_filter.admin.inc',
  );
  return $items;
}

/**
*  get content types for filter pages
*/

function content_filter_get_types() {
  $options = array();
  $types = node_type_get_types();
  $order_types = variable_get('content_filter_types', array());
  if (!empty($order_types)) {
    foreach ($order_types as $type => $val) {
      if (empty($types[$type]->name)) continue;
      $title = $types[$type]->name;
      if ($type == 'rich_media') $title .= 's';
      if ($type == 'subpage') $title = 'Pages';
      if ($type == 'category') $title = 'Categories';
      if ($val) $options[$type] = $title;
    }
    unset($options['subpage']);
    $result = array('subpage' => 'Pages') + $options;
    $options = $result;
  }
  return $options;
}
